### ISSUE TITLE
Exception tracking

### ISSUE THREAD

**Issue by wayneashleyberry** [putterschool/styleguide#10]
- [ ] Create a new [Sentry](https://app.getsentry.com/) project
- [ ] Integrate the [Sentry PHP client](https://app.getsentry.com/docs/platforms/php/)
  - [ ] Track application environment
  - [ ] Ignore exceptions in local environments
- [ ] Enable Slack notifications
